std::string relativeMoveTemplate = "<sequencer_prog><slave>0</slave><definitions><vars>WB_RampRelPos;WB_RampRelVar</vars><expr1>WB_RampRelPos = DATA_PHY(14)</expr1><expr2>WB_RampRelVar = WB_RampRelPos - 40</expr2></definitions><update><expressions>expr1;expr2</expressions></update><synth_set><unit>ramp</unit><type>ramp</type><stream>phys14</stream><stream2>phys15</stream2><rate>5</rate><end_rate>0</end_rate><acc>0</acc><end_ampl>WB_RampRelVar</end_ampl><end_time>50</end_time></synth_set><clear><triggers>TRIG_SYNTH_R</triggers></clear><start></start><wait><triggers>TRIG_SYNTH_R</triggers></wait><synth_set><unit>ramp</unit><type>const</type></synth_set><synth_set><unit>wave1</unit><type>reset</type></synth_set><synth_set><unit>wave2</unit><type>reset</type></synth_set><synth_set><unit>stream</unit><type>reset</type></synth_set><synth_set><unit>curve</unit><type>reset</type></synth_set><start></start></sequencer_prog>";


std::string absoluteMoveTemplate="<sequencer_prog><slave></slave><control_set><type>cascade</type><kp></kp><ti></ti><td></td><t1></t1><ke></ke><ke2></ke2><kff></kff><krei></krei><tau></tau><elim></elim><kdcc></kdcc><sym_man></sym_man><sym_adp></sym_adp><gki></gki><tki></tki><pk></pk><velocity_mode>no</velocity_mode></control_set><synth_set><unit>ramp</unit><type>acc</type><stream>phys14</stream><stream2>phys15</stream2><rate></rate><end_rate></end_rate><acc></acc><end_ampl></end_ampl></synth_set><clear><triggers>TRIG_SYNTH_R</triggers></clear><start></start><wait><triggers>TRIG_SYNTH_R</triggers></wait><synth_set><unit>ramp</unit><type>acc</type><rate></rate><end_rate></end_rate><acc></acc><end_ampl></end_ampl></synth_set><clear><triggers>TRIG_SYNTH_R</triggers></clear><start></start><wait><triggers>TRIG_SYNTH_R</triggers></wait><start></start></sequencer_prog>";

std::string moveWaitTemplate="<sequencer_prog><slave></slave><control_set><type>cascade</type><kp></kp><ti></ti><td></td><t1></t1><ke></ke><ke2></ke2><kff></kff><krei></krei><tau></tau><elim></elim><kdcc></kdcc><sym_man></sym_man><sym_adp></sym_adp><gki></gki><tki></tki><pk></pk><velocity_mode>no</velocity_mode></control_set><synth_set><unit>ramp</unit><type>acc</type><stream>phys1</stream><stream2>phys15</stream2><rate></rate><end_rate></end_rate><acc></acc><end_ampl></end_ampl></synth_set><clear><triggers>TRIG_SYNTH_R</triggers></clear><start></start><wait><triggers>TRIG_SYNTH_R</triggers></wait><synth_set><unit>ramp</unit><type>acc</type><rate></rate><end_rate></end_rate><acc></acc><end_ampl></end_ampl></synth_set><clear><triggers>TRIG_SYNTH_R</triggers></clear><start></start><wait><triggers>TRIG_SYNTH_R</triggers></wait><clear><triggers>TRIG_HOST</triggers></clear><host_send><string>3;-2;UserActionRequest;</string></host_send><wait><triggers>TRIG_HOST</triggers></wait><start></start></sequencer_prog>";
//std::string moveWaitTemplate="<sequencer_prog><slave>0</slave><control_set><type>cascade</type><kp>0.5</kp><ti>0.1</ti><td>0</td><t1>0.000125</t1><ke>4000</ke><ke2>0</ke2><kff>1000</kff><krei>0</krei><tau>0</tau><elim>0</elim><kdcc>0</kdcc><sym_man>0</sym_man><sym_adp>0</sym_adp><gki>0</gki><tki>0</tki><pk>0</pk><velocity_mode>no</velocity_mode></control_set><synth_set><unit>ramp</unit><type>acc</type><stream>phys1</stream><stream2>phys15</stream2><rate>0</rate><end_rate>0.02</end_rate><acc>0.02</acc><end_ampl>-0.08</end_ampl></synth_set><clear><triggers>TRIG_SYNTH_R</triggers></clear><start></start><wait><triggers>TRIG_SYNTH_R</triggers></wait><synth_set><unit>ramp</unit><type>acc</type><rate>5.000000</rate><end_rate>0.001000</end_rate><acc>10.000000</acc><end_ampl>-50.000000</end_ampl></synth_set><clear><triggers>TRIG_SYNTH_R</triggers></clear><start></start><wait><triggers>TRIG_SYNTH_R</triggers></wait><clear><triggers>TRIG_HOST</triggers></clear><host_send><string>3;-2;UserActionRequest;</string></host_send><wait><triggers>TRIG_HOST</triggers></wait><start></start></sequencer_prog>";

std::string absoluteSyncMoveTemplate="<sequencer_prog><slave>0</slave><sync><device></device></sync><wait><triggers>TRIG_SYNC</triggers></wait><synth_set><unit>ramp</unit><type>acc</type><stream>phys14</stream><stream2>phys15</stream2><rate>5</rate><end_rate>0</end_rate><acc>0</acc><end_ampl>10</end_ampl><end_time>50</end_time></synth_set><clear><triggers>TRIG_SYNTH_R</triggers></clear><start></start><wait><triggers>TRIG_SYNTH_R</triggers></wait><synth_set><unit>ramp</unit><type>const</type></synth_set><synth_set><unit>wave1</unit><type>reset</type></synth_set><synth_set><unit>wave2</unit><type>reset</type></synth_set><synth_set><unit>stream</unit><type>reset</type></synth_set><synth_set><unit>curve</unit><type>reset</type></synth_set><start></start></sequencer_prog>";

// Example sequencer, moves slave0 to -50 at 5mm/s
//<sequencer_prog><slave>0</slave><control_set><type>cascade</type><kp>0.5</kp><ti>0.05</ti><td>0</td><t1>0.000125</t1><ke>60</ke><ke2>0</ke2><kff>1200</kff><krei>0</krei><tau>0</tau><elim>0</elim><kdcc>0</kdcc><sym_man>0</sym_man><sym_adp>0</sym_adp><gki>0</gki><tki>0</tki><pk>1</pk><velocity_mode>no</velocity_mode></control_set><synth_set><unit>ramp</unit><type>acc</type><stream>phys14</stream><stream2>phys15</stream2><rate>0</rate><end_rate>5.000000</end_rate><acc>10.000000</acc><end_ampl>-48.750000</end_ampl></synth_set><clear><triggers>TRIG_SYNTH_R</triggers></clear><start></start><wait><triggers>TRIG_SYNTH_R</triggers></wait><synth_set><unit>ramp</unit><type>acc</type><rate>5.000000</rate><end_rate>0.001000</end_rate><acc>10.000000</acc><end_ampl>-50.000000</end_ampl></synth_set><clear><triggers>TRIG_SYNTH_R</triggers></clear><start></start><wait><triggers>TRIG_SYNTH_R</triggers></wait><start></start></sequencer_prog>